controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

error: 
    resource: ../templates/bundles/TwigBundle/Exception/error.html.twig
    type: annotation